place = ['3','2','5','1','4']
print(place)
print(sorted(place))
print(place)
print(sorted(place, reverse = True))
print(place)
place.reverse()
print(place)
place.reverse()
print(place)
place.sort()
print(place)
place.sort(reverse = True)
print(place)
